name: CI
on: ["push", "pull_request"]

jobs:
  test:
    name: Test contracts
    runs-on: ubuntu-latest
    env:
      REPORT_GAS: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Vault Harvester dependencies
        working-directory: ./vault-harvester
        run: yarn install --frozen-lockfile

      - name: Compile Vault Harvester contracts
        working-directory: ./vault-harvester
        run: yarn compile

      - name: Test Vault Harvester contracts
        working-directory: ./vault-harvester
        run: yarn test

      - name: Install Batch NFT Reveal dependencies
        working-directory: ./batch-nft-reveal
        run: yarn install --frozen-lockfile

      - name: Compile Batch NFT Reveal contracts
        working-directory: ./batch-nft-reveal
        run: yarn compile

      - name: Test Batch NFT Reveal contracts
        working-directory: ./batch-nft-reveal
        run: yarn test
